### ISSUE TITLE
Implementation is not the same as in paper

### ISSUE THREAD

**Issue by hackerekcah** [kingfengji/DeepMIML#3]
Softmax is applied on the labels axis, but not specify in paper.
Relu is not applied on conv(1,1), but said used in paper.

Thus the paper seems not matched and not reproducible, can you explain?

**Comment by kingfengji** [comment]
The main propose of this repo is to show how to build a customer layer such as sub-concept layers. ( It might be a little tricky for beginners to build such thing) The activations for the cub-concept layers, on the other hand, is quite flexible. 
For instance, ReLUs/Sigmoid/LinearMappings can be easily modified in the framework provided in this repo and it will be quite easy to create a ReLU sub-concept layer.

**Comment by hackerekcah** [comment]
Thanks, did you try different implementation and how did it influence the sub-concept layer?

**Comment by kingfengji** [comment]
Haven't tried all but basically they all produce a matching score (linear, sigmiod, relu or even tanh) and thus they are all reasonable choices, performance might be different depending on the datasets.
