### ISSUE TITLE
Any reason to add softmax here? seems not intuitive and not stated in paper

### ISSUE THREAD

**Issue by hackerekcah** [kingfengji/DeepMIML#4]
https://github.com/kingfengji/DeepMIML/blob/560fda2d96a71706dfacb7f1fb33ee56c7444600/lib/deepmiml/deepmiml.py#L39

**Comment by kingfengji** [comment]
thresholding at 0.5 actually is quite robust even for multi-label ( other than multi-class) but only in a practical point of view. you could comment that line off.
